name: Generate arcade animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: generate pacman graphs
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: 'pacman'
      
      - name: rename outputs
        run: |
          mkdir -p dist
          cp pacman-contribution-graph.svg dist/
          cp pacman-contribution-graph-dark.svg dist/ || true

      - name: Prepare output folder
        run: |
          mkdir -p dist
          cp *.svg dist/ || true

      - name: Deploy to pacman-output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: pacman-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
