name: Update Language Statistics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: StefVuck/Github-Language-Stats@v1.2.0
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          output_path: "stats"
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 15
          visualization_types: "leaderboard bar pie donut"
          include_forks: "true"
          exclude_languages: "html,blade,Dockerfile,batchfile,Hack,Shell,bash"
          use_loc: "true"
